on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre_check:
    name: Pre-check on Ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Ruff check
        uses: astral-sh/ruff-action@v3

  run_unit_test:
    needs: [pre_check]
    name: Run unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-14, macos-15-intel]
        python: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14', '3.14t']
        exclude:
          - os: macos-15-intel
            python: '3.13'
          - os: macos-15-intel
            python: '3.14'
          - os: macos-15-intel
            python: '3.14t'
            # The reason for the exclusion is that pytorch distribution
            # can't be found by pip on macos-15-intel with python 3.13.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Cache huggingface
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/huggingface
          key: huggingface-${{ matrix.os }}-python-${{ matrix.python }}

      - name: Build xgrammar from source
        run: |
          echo "set(XGRAMMAR_BUILD_CXX_TESTS ON)" >> cmake/config.cmake
          echo "set(XGRAMMAR_ENABLE_INTERNAL_CHECK ON)" >> cmake/config.cmake
          python -m pip install --upgrade pip
          pip install -v ".[test]"

      # Test with MLX (which is optional) under macOS arm64
      - name: Install MLX
        if: matrix.os == 'macos-14' && !endsWith(matrix.python, 't')
        run: |
          pip install mlx-lm

      - name: Run C++ tests
        run: |
          ctest --test-dir build -V --timeout 30 --stop-on-failure

      - name: Run Python tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_HUB_DOWNLOAD_TIMEOUT: 60
        if: env.HF_TOKEN != ''
        run: |
          pytest

      - name: Run Python tests without HF_TOKEN
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        if: env.HF_TOKEN == ''
        run: |
          pytest -m "not hf_token_required"

      - name: Run tests under pytest-run-parallel
        env:
          PYTHON_GIL: 0
        if: matrix.python == '3.14t'
        run: |
          python -m pip install pytest-run-parallel
          pytest -m "not hf_token_required" --parallel-threads=8
